[tool.poetry]
name = "code-augmentor-support"
version = "1.0.1"
description = "Enables the use of Python 3 to write code generator scripts for Code Augmentor"
authors = ["Aaron Baffour-Awuah <aaronbaffourawuah@gmail.com>"]
homepage = "https://github.com/aaronicsubstances/code-augmentor#readme"
repository = "https://github.com/aaronicsubstances/code-augmentor-python"
keywords = [ "code-generation", "data-driven", "macro-processor" ]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/aaronicsubstances/code-augmentor-python/issues"
