[tool.poetry]
name = "darwin_ml"
version = "0.1.0"
description = ""
authors = ["Kevin Hill <kivo360@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.3"
loguru = "^0.4.1"
creme = "^0.5.1"
jamboree = "0.8.8"
ta = "^0.5.25"
pydantic = "^1.5.1"
stochastic = "^0.4.0"
matplotlib = "^3.2.1"
toolz = "^0.10.0"
see137 = "^0.0.4"
cytoolz = "^0.10.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
yapf = "^0.30.0"
jupyter = "^1.0.0"
jupyterlab = "^2.1.2"
autopep8 = "^1.5.3"
twine = "^3.1.1"
wheel = "^0.34.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
