[tool.poetry]
name = "lic"
version = "0.1.1"
license = "MIT"
description = "Line integral convolution for numpy arrays"
authors = ["Steffen Brinkmann <s-b@mailbox.org>"]
readme = "README.rst"
repository = "https://gitlab.com/szs/lic/"
keywords = ["flow field", "vector field", "visualisation", "CFD", "plot"]
classifiers = ["Development Status :: 4 - Beta",
            "Intended Audience :: Science/Research",
            "License :: OSI Approved :: MIT License",
            "Programming Language :: Python :: 3",
            "Programming Language :: Python :: 3.6",
            "Programming Language :: Python :: 3.7",
            "Programming Language :: Python :: 3.8",
            "Topic :: Scientific/Engineering",
            "Topic :: Scientific/Engineering :: Visualization"]

[tool.poetry.dependencies]
python = "^3.6.1"
numpy = "^1.18.5"
matplotlib = "^3.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.9.0"
pytest-mypy = "^0.6.2"
pytest-flake8 = "^1.0.6"
ipython = "^7.15.0"
pytest-pylint = "^0.17.0"

[tool.poetry.scripts]
lic = 'lic.lic:py'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
