[tool.poetry]
name = "aidirectory"
version = "0.2.2"
description = ""
authors = ["mjaquier <mjaquier@me.com>"]

[tool.poetry.dependencies]
python = "3.8"
PyYAML = "^5.3.1"
oyaml = "^0.9"
simplelogging = "^0.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
