[tool.poetry]
name = "lx16a"
version = "0.0.1"
description = "Python library to control the Hiwonder LX-16a digital serial servo motor."
authors = ["Phil Winder <phil@WinderResearch.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://winderresearch.com"
repository = "https://gitlab.com/winderresearch/robotics/lx16a/"
documentation = "https://gitlab.com/winderresearch/robotics/lx16a/"
keywords = ["servo", "hiwonder", "robotics", "lx-16a"]

[tool.poetry.dependencies]
python = ">=3.6,<4"
pyserial = "^3.4"
loguru = "^0.5.0"
construct = "^2.10.56"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^5.4.3"
flake8 = "^3.8.3"
flake8-black = "^0.2.0"
safety = "^1.9.0"
bandit = "^1.6.2"
coverage = {extras = ["toml"], version = "^5.1"}
pytest-coverage = "^0.0"
codecov = "^2.1.4"

[tool.coverage.paths]
source = ["lx16a"]

[tool.coverage.run]
branch = true
source = ["lx16a"]

[tool.coverage.report]
show_missing = true
fail_under = 75

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

